Implementando Deep Learning

In [1]:
# Importação das bibliotecas
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
# Importando a base de dados
df = pd.read_csv('./data/survey_lung_cancer.csv')
df.head()

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0      M   69        1               2        2              1   
1      M   74        2               1        1              1   
2      F   59        1               1        1              2   
3      M   63        2               2        2              1   
4      F   63        1               2        1              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                1         2         1         2                  2         2   
1                2         2         2         1                  1         1   
2                1         2         1         2                  1         2   
3                1         1         1         1                  2         1   
4                1         1         1         2                  1         2   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    2                      2           2         YES  
1                    2                      2           2         YES  
2                    2                      1           2          NO  
3                    1                      2           2          NO  
4                    2                      1           1          NO

In [3]:
# Visualizando  o tamanho da base de dados
df.shape

(309, 16)

In [4]:
# Verificando se á dados duplicados
df.duplicated().sum()

33

In [5]:
# Excluído e verificando se á dados duplicados
df.drop_duplicates(keep='first', inplace=True)
df.duplicated().sum()

0

In [6]:
# Visualizando  o tamanho da base de dados e as informação
print(df.shape)
df.info()

(276, 16)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 276 entries, 0 to 283
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   GENDER                 276 non-null    object
 1   AGE                    276 non-null    int64 
 2   SMOKING                276 non-null    int64 
 3   YELLOW_FINGERS         276 non-null    int64 
 4   ANXIETY                276 non-null    int64 
 5   PEER_PRESSURE          276 non-null    int64 
 6   CHRONIC DISEASE        276 non-null    int64 
 7   FATIGUE                276 non-null    int64 
 8   ALLERGY                276 non-null    int64 
 9   WHEEZING               276 non-null    int64 
 10  ALCOHOL CONSUMING      276 non-null    int64 
 11  COUGHING               276 non-null    int64 
 12  SHORTNESS OF BREATH    276 non-null    int64 
 13  SWALLOWING DIFFICULTY  276 non-null    int64 
 14  CHEST PAIN             276 non-null    int64 
 15  LUNG_CANCER  

In [7]:
#separação dos variáveis
X = df.iloc[:,0:15].values
y = df.iloc[:, 15].values
X

array([['M', 69, 1, ..., 2, 2, 2],
       ['M', 74, 2, ..., 2, 2, 2],
       ['F', 59, 1, ..., 2, 1, 2],
       ...,
       ['M', 55, 2, ..., 2, 1, 2],
       ['M', 46, 1, ..., 1, 2, 2],
       ['M', 60, 1, ..., 2, 2, 2]], dtype=object)

In [8]:
#atribui valores
labelencoder = LabelEncoder()
X[:,0] = labelencoder.fit_transform(X[:,0])
X

array([[1, 69, 1, ..., 2, 2, 2],
       [1, 74, 2, ..., 2, 2, 2],
       [0, 59, 1, ..., 2, 1, 2],
       ...,
       [1, 55, 2, ..., 2, 1, 2],
       [1, 46, 1, ..., 1, 2, 2],
       [1, 60, 1, ..., 2, 2, 2]], dtype=object)

In [9]:
#Label encoder com a classe
labelencoder_Y = LabelEncoder()
y = labelencoder_Y.fit_transform(y)
y

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1])

In [ ]:
import numpy as np

np.reshape(X, (-1, 72, 72, 3)) 

In [10]:
# separação em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 0
)

In [11]:
#Feature Scalling, Padronização z-score
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
X_test

array([[ 1.19782411, -0.66770971,  0.93094934, -1.03637545, -1.03637545,
        -1.15470054, -1.24316312,  0.63245553, -1.        , -0.93094934,
        -0.96490128, -0.93094934, -1.29099445, -1.07417231, -1.03637545],
       [-0.83484711, -1.36943144, -1.07417231,  0.96490128,  0.96490128,
         0.8660254 ,  0.80439967,  0.63245553,  1.        ,  1.07417231,
        -0.96490128,  1.07417231,  0.77459667,  0.93094934, -1.03637545],
       [ 1.19782411, -0.9684476 , -1.07417231,  0.96490128,  0.96490128,
        -1.15470054,  0.80439967, -1.58113883,  1.        ,  1.07417231,
         1.03637545,  1.07417231, -1.29099445,  0.93094934, -1.03637545],
       [ 1.19782411, -0.06623394,  0.93094934, -1.03637545, -1.03637545,
        -1.15470054, -1.24316312,  0.63245553,  1.        ,  1.07417231,
         1.03637545,  1.07417231,  0.77459667, -1.07417231,  0.96490128],
       [-0.83484711, -0.66770971,  0.93094934,  0.96490128,  0.96490128,
         0.8660254 ,  0.80439967,  0.63245553, 

In [12]:
# Classificando
classifier = Sequential()
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_dim=15))
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
classifier.fit(X_train, y_train, batch_size=10, epochs=1024)

Epoch 1/1024
22/22 [==============================] - 19s 19ms/step - loss: 0.6887 - accuracy: 0.8500
Epoch 2/1024
22/22 [==============================] - 0s 7ms/step - loss: 0.6787 - accuracy: 0.8682
Epoch 3/1024
22/22 [==============================] - 0s 7ms/step - loss: 0.6651 - accuracy: 0.8682
Epoch 4/1024
22/22 [==============================] - 0s 8ms/step - loss: 0.6444 - accuracy: 0.8682
Epoch 5/1024
22/22 [==============================] - 0s 6ms/step - loss: 0.6141 - accuracy: 0.8682
Epoch 6/1024
22/22 [==============================] - 0s 6ms/step - loss: 0.5732 - accuracy: 0.8682
Epoch 7/1024
22/22 [==============================] - 0s 6ms/step - loss: 0.5217 - accuracy: 0.8682
Epoch 8/1024
22/22 [==============================] - 0s 7ms/step - loss: 0.4664 - accuracy: 0.8682
Epoch 9/1024
22/22 [==============================] - 0s 6ms/step - loss: 0.4132 - accuracy: 0.8682
Epoch 10/1024
22/22 [==============================] - 0s 7ms/step - loss: 0.3681 - accuracy: 0.86

In [13]:
# Criando uma previsão
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

2/2 [==============================] - 1s 3ms/step


array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False]])

In [14]:
# matriz de confusão
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 5,  4],
       [ 3, 44]], dtype=int64)